import createClient, { type Middleware } from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

const myMiddleware: Middleware = {
    async onRequest({ request, options }) {
        // set "foo" header
        const accessToken = localStorage.getItem('musicfan-accessToken');
        if (accessToken) {
            request.headers.set('Authorization', `Bearer ${accessToken}`);
        }

        return request;
    },
    onResponse({ response }) {
        if (!response.ok) {
            // Will produce error messages like "https://example.org/api/v1/example: 404 Not Found".
            throw new Error(`${response.url}: ${response.status} ${response.statusText}`)
        }
    }
};

const client = createClient<paths>({ baseUrl: "https://musicfun.it-incubator.app/api/1.0/", headers: {
    "api-key": "b24ee7ff-d9a9-4404-bb94-aead42c29c9e",
} });

client.use(myMiddleware);

export default client;