import createClient from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: "https://musicfun.it-incubator.app/api/1.0/", headers: {
    "api-key": "b24ee7ff-d9a9-4404-bb94-aead42c29c9e",
} });

export default client;